name=mwos
version=3.5.260413
author=Vladimir M. <vladimir9@bk.ru>
maintainer=Vladimir <vladimir9@bk.ru>
sentence=MWOS modules OS
paragraph=Modular operating system for IoT microcontrollers. Enables remote monitoring and control of devices via unified web interface and cross-platform app. Module-based architecture lets you focus on device logic while MWOS handles networking, web server, settings storage, communication protocols, and cloud sync. Supports 100+ Arduino Framework compatible boards (AVR, ESP8266, ESP32, STM32, RP2040, etc.), features MWScript scripting language and universal binary protocol over WiFi, Ethernet, USB, RS232/485, CAN, and radio links.
category=Communication, OS
url=https://github.com/voscom/mwos
architectures=*
