; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/platformio/platform-espressif32.git
framework = arduino
monitor_speed = 115200
extra_scripts = pre:version_git.py
build_type = debug
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder
lib_deps = 
	EEPROM
	WS2812FX
	WiFi
	BLE
	WebServer
	TwoWire
	HTTPClient
	;https://github.com/pstolarz/OneWireNg.git
	;https://github.com/RobTillaart/DHTNew.git
	https://github.com/crankyoldgit/IRremoteESP8266.git
	https://github.com/plerup/espsoftwareserial.git
	https://gitlab.com/free_mwos/ethernet
	https://github.com/JAndrassy/ArduinoOTA.git
	git+https://github.com/me-no-dev/AsyncTCP
	https://github.com/xreef/SimpleFTPServer.git
	https://github.com/adafruit/Adafruit_SSD1306.git
	https://github.com/immortalserg/AdafruitGFXRusFonts

[env:esp32-c3-LuatOS-simple]
board = esp32-c3-LuatOS
framework = arduino
build_flags = 
	-D STELLA_PC

[env:esp32-c3-LuatOS-simple-secure]
extends = env:esp32-c3-LuatOS-simple
upload_command = python -m esptool --port $UPLOAD_PORT --baud $UPLOAD_SPEED write_flash --encrypt 0x0 .pio/build/$PIOENV/bootloader.bin 0x8000 .pio/build/$PIOENV/partitions.bin 0x10000 .pio/build/$PIOENV/firmware.bin
build_flags = 
	${env:esp32-c3-LuatOS-simple.build_flags}
	-DCONFIG_SECURE_FLASH_ENC_ENABLED=1
	-DCONFIG_SECURE_FLASH_ENCRYPTION_MODE_DEVELOPMENT=1
board_build.embed_txtfiles = 
	crypt/my_flash_encryption_key.bin

[env:esp32-c3-LuatOS-stella]
board = esp32-c3-LuatOS
build_flags = 
	-D STELLA_STELLA

[env:esp32-c3-supermini]
board = esp32-c3-supermini
build_flags = 
	-D STELLA_PC

[env:esp32-c3-supermini-stella]
board = esp32-c3-supermini
build_flags = 
	-D STELLA_STELLA

[env:esp32s3-n16r8v]
board = esp32-s3-devkitc-1-n16r8v
build_flags = 
	-D STELLA_PC

[env:esp32s3-n8r2]
board = esp32-s3-devkitc-1-n8r2
build_flags = 
	-D STELLA_PC

[env:esp32s3-n16r8v-mw]
board = esp32-s3-devkitc-1-n16r8v
build_flags = 
	-D CID=1

[env:esp32-c3-LuatOS-mw]
board = esp32-c3-LuatOS
build_flags = 
	-D CID=2

[env:esp32s3-n8r2-mw]
board = esp32-s3-devkitc-1-n8r2
build_flags =
	-D CID=1

[env:esp32-c3-supermini-mw]
board = esp32-c3-supermini
build_flags = 
	-D CID=1

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
